#requires -Version 5.1
Set-StrictMode -Version Latest

$sourceFiles = @(
    'src/Core/Common.ps1',
    'src/Core/Config.ps1',
    'src/Core/Cache.ps1',
    'src/Core/Localization.ps1',
    'src/Core/Logger.ps1',
    'src/Core/Update.ps1',
    'src/Core/Manifest.ps1',
    'src/Core/ProcessRunner.ps1',
    'src/Core/State.ps1',
    'src/Core/Assistant.ps1',
    'src/Core/Bootstrap.ps1',
    'src/Scanner/Platform.ps1',
    'src/Scanner/Hardware.ps1',
    'src/Scanner/Network.ps1',
    'src/Scanner/System.ps1',
    'src/Scanner/Activation.ps1',
    'src/Scanner/Readiness.ps1',
    'src/Scanner/Software.ps1',
    'src/Scanner/WindowsUpdate.ps1',
    'src/Drivers/DriverScanner.ps1',
    'src/Drivers/DriverResolver.ps1',
    'src/Operations/Common.ps1',
    'src/Operations/DriverBackup.ps1',
    'src/Operations/NetworkRescue.ps1',
    'src/Operations/SecurityStatus.ps1',
    'src/Operations/Diagnostics.ps1',
    'src/Operations/PreReset.ps1',
    'src/Operations/DduRecovery.ps1',
    'src/Packages/Catalog.ps1',
    'src/Packages/Compatibility.ps1',
    'src/Packages/Detector.ps1',
    'src/Packages/Resolver.ps1',
    'src/Packages/Installer.ps1',
    'src/Packages/Verifier.ps1',
    'src/Recommendation/Profiles.ps1',
    'src/Recommendation/Rules.ps1',
    'src/Execution/Planner.ps1',
    'src/Execution/Progress.ps1',
    'src/Execution/Resume.ps1',
    'src/Execution/Elevation.ps1',
    'src/Execution/Queue.ps1',
    'src/UI/Input.ps1',
    'src/UI/Selection.ps1',
    'src/UI/Terminal.ps1',
    'src/Core/Validation.ps1',
    'src/UI/Cli.ps1'
)

foreach ($relativePath in $sourceFiles) {
    $path = Join-Path $PSScriptRoot $relativePath
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "FreshWin source file is missing: $relativePath" }
    . $path
}

$publicFunctions = @(
    'Get-FreshWinVersion', 'Get-FreshWinSupportedLocale', 'Get-FreshWinPaths',
    'Initialize-FreshWinEnvironment', 'New-FreshWinConfig', 'Get-FreshWinConfig',
    'Save-FreshWinConfig', 'Set-FreshWinConfigLocale', 'Set-FreshWinConfigCompactMode', 'Initialize-FreshWinLocalization',
    'Get-FreshWinCacheEntry', 'Set-FreshWinCacheEntry', 'Remove-FreshWinCacheEntry',
    'Set-FreshWinLocale', 'Get-FreshWinString', 'Initialize-FreshWinLogger',
    'Get-FreshWinLogPath', 'Get-FreshWinLogHistory', 'Write-FreshWinLog', 'Protect-FreshWinSensitiveText', 'Invoke-FreshWinProcess',
    'Test-FreshWinUpdateMetadata', 'Get-FreshWinUpdateStatus', 'Save-FreshWinUpdatePackage', 'Invoke-FreshWinCoreUpdate',
    'Test-FreshWinPackageManifest', 'Import-FreshWinPackageManifest',
    'Import-FreshWinPackageCatalog', 'Get-FreshWinPackage', 'Find-FreshWinPackage',
    'Test-FreshWinCatalogIntegrity', 'Test-FreshWinLocalizationResources',
    'Test-FreshWinProfiles', 'Test-FreshWinProject', 'ConvertFrom-FreshWinAssistantCommand',
    'Register-FreshWinAssistantProvider', 'Get-FreshWinAssistantProvider',
    'Invoke-FreshWinAssistantProvider', 'Initialize-FreshWinRuntime',
    'Get-FreshWinPlatformName', 'Test-FreshWinWindows',
    'Test-FreshWinAdministrator', 'Get-FreshWinHardwareInfo', 'Get-FreshWinNetworkState',
    'Get-FreshWinSystemInfo', 'Get-FreshWinActivationStatus', 'Get-FreshWinWindows11Readiness',
    'Get-FreshWinSoftwareInventory', 'Get-FreshWinSoftwareInventorySnapshot',
    'Get-FreshWinWindowsUpdateState', 'Get-FreshWinDriverInventory', 'Get-FreshWinDriverSummary',
    'Get-FreshWinMissingDrivers', 'Get-FreshWinGpuDriverRecommendation', 'Get-FreshWinDduWorkflow',
    'New-FreshWinDriverBackup', 'Get-FreshWinDriverBackupInventory',
    'New-FreshWinDriverRestorePlan',
    'Find-FreshWinLocalNetworkDriver', 'Get-FreshWinNetworkRescueState',
    'New-FreshWinNetworkRescuePlan', 'Invoke-FreshWinNetworkRescueRetry',
    'Get-FreshWinOfflineNetworkDiagnostics', 'Get-FreshWinSecurityStatus',
    'Get-FreshWinDiagnostics', 'Get-FreshWinHealthSummary',
    'Export-FreshWinDiagnostics', 'Get-FreshWinPreResetObservations',
    'New-FreshWinPreResetPlan', 'Set-FreshWinPreResetChecklistItem',
    'Test-FreshWinPreResetPlan', 'Test-FreshWinDduReplacementArtifact',
    'New-FreshWinDduRecoveryPlan', 'Move-FreshWinDduRecoveryPlan',
    'Test-FreshWinDduRecoveryPlan', 'Save-FreshWinDduRecoveryCheckpoint',
    'Get-FreshWinDduRecoveryCheckpoint',
    'Get-FreshWinPackageCompatibility', 'Get-FreshWinPackageDetection', 'Get-FreshWinCatalogState',
    'Resolve-FreshWinPackageSource', 'Invoke-FreshWinPackageInstall',
    'Test-FreshWinPackageVerification', 'Import-FreshWinProfiles', 'Get-FreshWinProfile',
    'Export-FreshWinProfile', 'Import-FreshWinUserProfile', 'Get-FreshWinRecommendations',
    'Get-FreshWinMissingRecommendations', 'New-FreshWinInstallPlan', 'Test-FreshWinInstallPlan',
    'Save-FreshWinInstallPlan', 'Get-FreshWinExecutionSummary', 'Invoke-FreshWinExecutionPlan',
    'Get-FreshWinDefaultCheckpointPath', 'Save-FreshWinExecutionCheckpoint',
    'Get-FreshWinExecutionCheckpoint', 'Restore-FreshWinPlanFromCheckpoint',
    'Remove-FreshWinExecutionCheckpoint', 'Register-FreshWinResume', 'Unregister-FreshWinResume',
    'Get-FreshWinPlanElevationRequirement', 'Test-FreshWinElevationSourceTrust', 'Invoke-FreshWinElevatedResume',
    'ConvertFrom-FreshWinSelection', 'ConvertFrom-FreshWinCommandLine',
    'Format-FreshWinTerminalPage', 'Start-FreshWinTerminalSession',
    'Invoke-FreshWinCli', 'Start-FreshWinInteractive'
)

Export-ModuleMember -Function $publicFunctions
